# SAM deployment configuration
# Values here are used by 'sam deploy' (no need to pass --parameter-overrides)

version = 0.1

[default.deploy.parameters]
stack_name = "vibecast-lambda"
resolve_s3 = true
s3_prefix = "vibecast-lambda"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

parameter_overrides = "InputBucket=\"vibecast-ftp\" OutputBucket=\"vibecast-ftp\" ResultsBucket=\"vibecast-ftp\" OpenAISecretName=\"vibecast/openai\" NovitaSecretName=\"vibecast/novita\" EnableApiGateway=\"true\""
image_repositories = []

[default.build.parameters]
use_container = false
